version: "3.8"
services:
  note-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-service:latest
    container_name: note-service
    ports:
      - "8085:8085"
    environment:
      - SERVER_PORT=8085
      - SPRING_DATA_MONGODB_URI=mongodb://root:password@mongo:27017/?authSource=admin
      - SPRING_DATA_MONGODB_DATABASE=note
    depends_on:
      - mongo
  mongo:
    image: mongo:5.0
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=note
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - db_data:./database/db:/data/db
      - dev_archive:./database/dev.archive:/Databases/dev.archive
      - production_data:./database/production:/Databases/production
  mongo-express:
    image: mongo-express
    container_name: mexpress
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    links:
      - mongo
    restart: unless-stopped
    ports:
      - "8081:8081"

volumes:
  db_data:
  dev_archive:
  production_data: