server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${URI_PATH:/}
  tomcat:
    use-relative-redirects: true

access-token:
  private: ${ACCESS_TOKEN_PRIVATE_KEY_PATH}
  public: ${ACCESS_TOKEN_PUBLIC_KEY_PATH}
refresh-token:
  private: ${REFRESH_TOKEN_PRIVATE_KEY_PATH}
  public: ${REFRESH_TOKEN_PUBLIC_KEY_PATH}

spring:
  profiles:
    active: dev
  application:
    name: note-service
  data:
    mongodb:
      uri: mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_HOST}:27017/?authSource=admin
      database: ${MONGODB_DB:note}